la_election_results:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: la-election-results
      dataset: la_election_results # You can also use "schema" here
      threads: 1 # Must be a value of 1 or greater
      keyfile: /workspaces/la-election-results/env/keyfile.json
